dist: bionic
language: minimal

# Environment variables
env:
  global:
    - VLC_VERSION=3.0.99
    #- GRADLE_VERSION=5.1.1
    - SDK_REVISION=4333796
    - NDK_VERSION=r18b

# Install build dependencies
before_install:
  - sudo apt update
  - sudo apt install -y automake ant autopoint cmake build-essential libtool-bin \
      patch pkg-config protobuf-compiler ragel subversion unzip git \
      openjdk-8-jre openjdk-8-jdk flex python wget

# Download both Android SDK and NDK
install:
  - wget -q https://dl.google.com/android/repository/sdk-tools-linux-$SDK_REVISION.zip
  - mkdir $HOME/android-sdk && unzip -q sdk-tools-linux-$SDK_REVISION.zip -d $HOME/android-sdk
  - rm sdk-tools-linux-$SDK_REVISION.zip
  - wget -q https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux-x86_64.zip
  - unzip -q android-ndk-$NDK_VERSION-linux-x86_64.zip -d $HOME
  - rm android-ndk-$NDK_VERSION-linux-x86_64.zip
  - export ANDROID_SDK=$HOME/android-sdk
  - export ANDROID_NDK=$HOME/android-ndk-$NDK_VERSION
  - export PATH=$PATH:$ANDROID_SDK/platform-tools:$ANDROID_SDK/tools

# Download VLC Android source
before_script:
  - git clone https://code.videolan.org/videolan/vlc-android.git
  - git -C ./vlc-android checkout tags/$VLC_VERSION
  #- sed -i -e "s/GRADLE_VERSION=[0-9\\.]\\+/GRADLE_VERSION=$GRADLE_VERSION/" ./vlc-android/compile.sh

# Build libVLC
script:
  - cd ./vlc-android
  - sh ./compile.sh -l -a armeabi-v7a -r >/dev/null
  #- sh ./compile.sh -l -a all -r >/dev/null

# Update this repository
after_script:
  - cd ..
  - ls ./vlc-android/libvlc/build/outputs/aar -al
  #- ls ./vlc-android/libvlc/src/org -al
  #- if [ -d ./libvlc ]; then rm -rf ./libvlc; fi
  #- rm -rf ./vlc-android

# Publish final AARs
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: vlc-android/libvlc/build/outputs/aar/*
  skip_cleanup: true
  on:
    tags: true
