dist: bionic
language: minimal

# Build configuration
branches:
  only:
    - master

# Environment variables
env:
  global:
    - VLC_VERSION=3.1.7
    - SDK_REVISION=4333796
    - NDK_VERSION=r18b
    - GRADLE_VERSION=5.1.1
    - IS_TEST_RUN=false
  matrix:
    - ARCH=armeabi-v7a
    - ARCH=arm64-v8a
    - ARCH=x86
    - ARCH=x86_64

# Define dependencies
addons:
  apt:
    update: true
    packages:
      - automake
      - ant
      - autopoint
      - cmake
      - build-essential
      - libtool-bin
      - patch
      - pkg-config
      - protobuf-compiler
      - ragel
      - openjdk-8-jre
      - openjdk-8-jdk

# Download both Android SDK and NDK
install:
  - wget -q https://dl.google.com/android/repository/sdk-tools-linux-$SDK_REVISION.zip
  - mkdir $HOME/android-sdk && unzip -q sdk-tools-linux-$SDK_REVISION.zip -d $HOME/android-sdk
  - rm sdk-tools-linux-$SDK_REVISION.zip
  - wget -q https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux-x86_64.zip
  - unzip -q android-ndk-$NDK_VERSION-linux-x86_64.zip -d $HOME
  - rm android-ndk-$NDK_VERSION-linux-x86_64.zip
  - export ANDROID_SDK=$HOME/android-sdk
  - export ANDROID_NDK=$HOME/android-ndk-$NDK_VERSION
  - export PATH=$PATH:$ANDROID_SDK/platform-tools:$ANDROID_SDK/tools

# Download VLC Android source
before_script:
  - git clone https://code.videolan.org/videolan/vlc-android.git
  - git -C ./vlc-android checkout tags/$VLC_VERSION

# Build libVLC
script:
  - cd ./vlc-android
  # Change Gradle configuration
  - echo "org.gradle.parallel=true" >> gradle.properties
  - echo "org.gradle.configureondemand=true" >> gradle.properties
  - echo "org.gradle.daemon=true" >> gradle.properties
  - echo "org.gradle.jvmargs=-Xmx4096M" >> gradle.properties
  # Initialize and download Gradle
  - mkdir -p ./gradle/wrapper
  - sh ./compile.sh --init
  - wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
  - unzip -q gradle-$GRADLE_VERSION-bin.zip
  - sh ./gradle-$GRADLE_VERSION/bin/gradle wrapper
  - chmod a+x gradlew
  - rm gradle-$GRADLE_VERSION-bin.zip
  # Execute compile script
  - sh ./compile.sh -l -a $ARCH -r >/dev/null
  - cd ..

# Prepare repository before deploying
after_success:
  # Extract binaries from AAR
  - JNILIBS_DIR=$PWD/libvlc/src/main/jniLibs/$ARCH
  - if [ -d $JNILIBS_DIR ]; then rm -rf $JNILIBS_DIR; fi
  - mkdir -p $JNILIBS_DIR
  - unzip -j ./vlc-android/libvlc/build/outputs/aar/*.aar "jni/$ARCH/*" -d $JNILIBS_DIR
  # Copy source classes
  - SOURCES_DIR=$PWD/libvlc/src/main/java
  - if [ -d $SOURCES_DIR ]; then rm -rf $SOURCES_DIR; fi
  - mkdir -p $SOURCES_DIR
  - cp -r ./vlc-android/libvlc/src/* $SOURCES_DIR/
  # Copy resource files
  - RES_DIR=$PWD/libvlc/src/main/res
  - if [ -d $RES_DIR ]; then rm -rf $RES_DIR; fi
  - mkdir -p $RES_DIR
  - cp -r ./vlc-android/libvlc/res/* $RES_DIR/
  # Get compiled libVLC version name
  - export LIBVLC_VERSION=$(ls ./vlc-android/libvlc/build/outputs/aar/*.aar | sed 's/.aar//g' | awk -F '-' '{print $NF}')

# Deploy to GitHub
deploy:
  provider: script
  script: sh travis_deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $IS_TEST_RUN = false
